/* soapC.cpp
   Generated by gSOAP 2.2.3b from Authentication.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapC.cpp ver 2.2.3b 2003-06-12 15:43:33 GMT")


#ifndef WITH_NOGLOBAL

SOAP_FMAC1 void SOAP_FMAC2 soap_serializeheader(struct soap *soap)
{
	soap_serialize_SOAP_ENV__Header(soap, soap->header);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_putheader(struct soap *soap)
{
	if (soap->header)
	{	soap->is_in_header = 1;
		soap_out_SOAP_ENV__Header(soap, "SOAP-ENV:Header", 0, soap->header, NULL);
		soap->is_in_header = 0;
	}
	return SOAP_OK;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_getheader(struct soap *soap)
{
	soap->is_in_header = 1;
	soap->header = soap_in_SOAP_ENV__Header(soap, "SOAP-ENV:Header", NULL, NULL);
	soap->is_in_header = 0;
	return soap->header == NULL;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_fault(struct soap *soap)
{
	if (!soap->fault)
	{	soap->fault = (struct SOAP_ENV__Fault*)soap_malloc(soap, sizeof(struct SOAP_ENV__Fault));
		soap_default_SOAP_ENV__Fault(soap, soap->fault);
	}
	if (soap->version == 2 && !soap->fault->SOAP_ENV__Code)
	{	soap->fault->SOAP_ENV__Code = (struct SOAP_ENV__Code*)soap_malloc(soap, sizeof(struct SOAP_ENV__Code));
		soap_default_SOAP_ENV__Code(soap, soap->fault->SOAP_ENV__Code);
	}
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serializefault(struct soap *soap)
{
	soap_serialize_SOAP_ENV__Fault(soap, soap->fault);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_putfault(struct soap *soap)
{
	return soap_out_SOAP_ENV__Fault(soap, "SOAP-ENV:Fault", 0, soap->fault, NULL);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_getfault(struct soap *soap)
{
	return (soap->fault = soap_in_SOAP_ENV__Fault(soap, "SOAP-ENV:Fault", NULL, NULL)) == NULL;
}

SOAP_FMAC1 const char ** SOAP_FMAC2 soap_faultcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Value;
	return (const char**)&soap->fault->faultcode;
}

SOAP_FMAC1 const char ** SOAP_FMAC2 soap_faultstring(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Reason;
	return (const char**)&soap->fault->faultstring;
}

SOAP_FMAC1 const char ** SOAP_FMAC2 soap_faultdetail(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Detail;
	return (const char**)&soap->fault->detail;
}

#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_getindependent(struct soap *soap)
{
	for (;;)
	{	if (soap_peek_element(soap))
			break;
		switch (soap_lookup_type(soap, soap->id))
		{
		case SOAP_TYPE_byte:
			soap_in_byte(soap, NULL, NULL, "");
			break;
		case SOAP_TYPE_int:
			soap_in_int(soap, NULL, NULL, "");
			break;
		case SOAP_TYPE_xsd__boolean:
			soap_in_xsd__boolean(soap, NULL, NULL, "xsd:boolean");
			break;
		case SOAP_TYPE_Enum_:
			soap_in_Enum_(soap, NULL, NULL, "");
			break;
		case SOAP_TYPE_tns__getAttributes:
			soap_in_tns__getAttributes(soap, NULL, NULL, "tns:getAttributes");
			break;
		case SOAP_TYPE_tns__requestSession:
			soap_in_tns__requestSession(soap, NULL, NULL, "tns:requestSession");
			break;
		case SOAP_TYPE_tns__Attribute:
			soap_in_tns__Attribute(soap, NULL, NULL, "tns:Attribute");
			break;
		case SOAP_TYPE_tns__requestSessionResponse:
			soap_in_tns__requestSessionResponse(soap, NULL, NULL, "tns:requestSessionResponse");
			break;
		case SOAP_TYPE_ArrayOfstring:
			soap_in_ArrayOfstring(soap, NULL, NULL, "xsd:string");
			break;
		case SOAP_TYPE_tns__getAttributesResponse:
			soap_in_tns__getAttributesResponse(soap, NULL, NULL, "tns:getAttributesResponse");
			break;
		case SOAP_TYPE_ArrayOfAttribute:
			soap_in_ArrayOfAttribute(soap, NULL, NULL, "tns:Attribute");
			break;
		case SOAP_TYPE_PointerTotns__getAttributesResponse:
			soap_in_PointerTotns__getAttributesResponse(soap, NULL, NULL, "tns:getAttributesResponse");
			break;
		case SOAP_TYPE_PointerTotns__requestSessionResponse:
			soap_in_PointerTotns__requestSessionResponse(soap, NULL, NULL, "tns:requestSessionResponse");
			break;
		case SOAP_TYPE_PointerTotns__Attribute:
			soap_in_PointerTotns__Attribute(soap, NULL, NULL, "tns:Attribute");
			break;
		case SOAP_TYPE_PointerToArrayOfstring:
			soap_in_PointerToArrayOfstring(soap, NULL, NULL, "xsd:string");
			break;
		case SOAP_TYPE_PointerToxsd__string:
			soap_in_PointerToxsd__string(soap, NULL, NULL, "xsd:string");
			break;
		case SOAP_TYPE_PointerToArrayOfAttribute:
			soap_in_PointerToArrayOfAttribute(soap, NULL, NULL, "tns:Attribute");
			break;
		case SOAP_TYPE_xsd__string:
			soap_in_xsd__string(soap, NULL, NULL, "xsd:string");
			break;
		case SOAP_TYPE_string:
			soap_in_string(soap, NULL, NULL, "");
			break;
		default:
			if (!*soap->id)
			{	if (soap_ignore_element(soap))
					break;
				else
					continue;
			}
			soap_in_byte(soap, NULL, NULL, "xsd:byte");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_int(soap, NULL, NULL, "xsd:int");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_xsd__boolean(soap, NULL, NULL, "xsd:boolean");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_Enum_(soap, NULL, NULL, "Enum");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_tns__getAttributes(soap, NULL, NULL, "tns:getAttributes");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_tns__requestSession(soap, NULL, NULL, "tns:requestSession");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_tns__Attribute(soap, NULL, NULL, "tns:Attribute");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_tns__requestSessionResponse(soap, NULL, NULL, "tns:requestSessionResponse");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_ArrayOfstring(soap, NULL, NULL, "xsd:string");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_tns__getAttributesResponse(soap, NULL, NULL, "tns:getAttributesResponse");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_ArrayOfAttribute(soap, NULL, NULL, "tns:Attribute");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_xsd__string(soap, NULL, NULL, "xsd:string");
			if (soap->error == SOAP_TYPE_MISMATCH && soap->level == 2)
				soap_in_string(soap, NULL, NULL, "xsd:string");
			if (soap->error)
			{	soap->peeked = 1;
				soap_ignore_element(soap);
			}
		}
		if (soap->error)
			break;
	}
	if (soap->error == SOAP_NO_TAG)
		soap->error = SOAP_OK;
	return soap->error;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_putindependent(struct soap *soap)
{
	int i;
	struct soap_plist *pp;
	if (soap->version != 1 || (soap->mode & SOAP_XML_GRAPH) || (soap->mode & SOAP_XML_TREE))
		return SOAP_OK;
	for (i = 0; i < SOAP_PTRHASH; i++)
		for (pp = soap->pht[i]; pp; pp = pp->next)
			if ((soap->mode & SOAP_IO_LENGTH) ? pp->mark1 == 2 : pp->mark2 == 2)
				switch (pp->type)
				{
				case SOAP_TYPE_byte:
					soap_out_byte(soap, "id", pp->id, (const char *)pp->ptr, "xsd:byte");
					break;
				case SOAP_TYPE_int:
					soap_out_int(soap, "id", pp->id, (const int *)pp->ptr, "xsd:int");
					break;
				case SOAP_TYPE_xsd__boolean:
					soap_out_xsd__boolean(soap, "id", pp->id, (const enum Enum_ *)pp->ptr, "xsd:boolean");
					break;
				case SOAP_TYPE_Enum_:
					soap_out_Enum_(soap, "id", pp->id, (const enum Enum_ *)pp->ptr, "Enum");
					break;
				case SOAP_TYPE_tns__getAttributes:
					soap_out_tns__getAttributes(soap, "id", pp->id, (const struct tns__getAttributes *)pp->ptr, "tns:getAttributes");
					break;
				case SOAP_TYPE_tns__requestSession:
					soap_out_tns__requestSession(soap, "id", pp->id, (const struct tns__requestSession *)pp->ptr, "tns:requestSession");
					break;
				case SOAP_TYPE_tns__Attribute:
					soap_out_tns__Attribute(soap, "id", pp->id, (const struct tns__Attribute *)pp->ptr, "tns:Attribute");
					break;
				case SOAP_TYPE_tns__requestSessionResponse:
					soap_out_tns__requestSessionResponse(soap, "id", pp->id, (const struct tns__requestSessionResponse *)pp->ptr, "tns:requestSessionResponse");
					break;
				case SOAP_TYPE_ArrayOfstring:
					soap_out_ArrayOfstring(soap, "id", pp->id, (const struct ArrayOfstring *)pp->ptr, "xsd:string");
					break;
				case SOAP_TYPE_tns__getAttributesResponse:
					soap_out_tns__getAttributesResponse(soap, "id", pp->id, (const struct tns__getAttributesResponse *)pp->ptr, "tns:getAttributesResponse");
					break;
				case SOAP_TYPE_ArrayOfAttribute:
					soap_out_ArrayOfAttribute(soap, "id", pp->id, (const struct ArrayOfAttribute *)pp->ptr, "tns:Attribute");
					break;
				case SOAP_TYPE_PointerTotns__getAttributesResponse:
					soap_out_PointerTotns__getAttributesResponse(soap, "id", pp->id, (struct tns__getAttributesResponse *const*)pp->ptr, "tns:getAttributesResponse");
					break;
				case SOAP_TYPE_PointerTotns__requestSessionResponse:
					soap_out_PointerTotns__requestSessionResponse(soap, "id", pp->id, (struct tns__requestSessionResponse *const*)pp->ptr, "tns:requestSessionResponse");
					break;
				case SOAP_TYPE_PointerTotns__Attribute:
					soap_out_PointerTotns__Attribute(soap, "id", pp->id, (struct tns__Attribute *const*)pp->ptr, "tns:Attribute");
					break;
				case SOAP_TYPE_PointerToArrayOfstring:
					soap_out_PointerToArrayOfstring(soap, "id", pp->id, (struct ArrayOfstring *const*)pp->ptr, "xsd:string");
					break;
				case SOAP_TYPE_PointerToxsd__string:
					soap_out_PointerToxsd__string(soap, "id", pp->id, (char **const*)pp->ptr, "xsd:string");
					break;
				case SOAP_TYPE_PointerToArrayOfAttribute:
					soap_out_PointerToArrayOfAttribute(soap, "id", pp->id, (struct ArrayOfAttribute *const*)pp->ptr, "tns:Attribute");
					break;
				case SOAP_TYPE_xsd__string:
					soap_out_string(soap, "id", pp->id, (char**)&pp->ptr, "xsd:string");
					break;
				case SOAP_TYPE_string:
					soap_out_string(soap, "id", pp->id, (char**)&pp->ptr, "xsd:string");
					break;
				}
		
	return SOAP_OK;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_getattachments(struct soap *soap)
{
	if (!(soap->mode & SOAP_ENC_DIME))
		return SOAP_OK;
	while (soap->dime_flags & SOAP_DIME_CF)
	{	if (soap_getdimehdr(soap))
			return soap->error;
		if (soap_move(soap, soap->dime_size))
			return soap->error = SOAP_EOF;
	}
	if (soap_move(soap, ((soap->dime_size+3)&-4)-soap_tell(soap)))
		return soap->error = SOAP_EOF;
	for (;;)
	{	if (soap_getdime(soap) || !soap->dime_id)
			break;
		switch (soap_lookup_type(soap, soap->dime_id))
		{
		case SOAP_TYPE_xsd__string:
		{	char ** a;
			a = (char **)soap_id_enter(soap, soap->dime_id, NULL, SOAP_TYPE_xsd__string, sizeof(char *), 0);
			if (a)
				*a = soap->dime_ptr;
			break;
		}
		case SOAP_TYPE_string:
		{	char ** a;
			a = (char **)soap_id_enter(soap, soap->dime_id, NULL, SOAP_TYPE_string, sizeof(char *), 0);
			if (a)
				*a = soap->dime_ptr;
			break;
		}
		default:
			soap->error = SOAP_DIME_ERROR;
		}
		if (soap->error)
			break;
	}
	if (soap->error == SOAP_EOD)
		soap->error = SOAP_OK;
	return soap->error;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_putattachments(struct soap *soap)
{
	int i;
	struct soap_plist *pp;
	if (!(soap->mode & SOAP_ENC_DIME))
		return SOAP_OK;
	if (soap_send_raw(soap, "\0\0\0", -(int)soap->count&3))
		return soap->error;
	for (i = 0; i < SOAP_PTRHASH; i++)
		for (pp = soap->pht[i]; pp; pp = pp->next)
			if (pp->mark2 == 3)
				switch (pp->type)
				{
				}
		
	return SOAP_OK;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_byte(struct soap *soap, char *a)
{
#ifdef SOAP_DEFAULT_byte
	*a = SOAP_DEFAULT_byte;
#else
	*a = (char)0;
#endif
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_byte(struct soap *soap, char const*a)
{
	soap_reference(soap, a, SOAP_TYPE_byte);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_byte(struct soap *soap, char *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_byte, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_byte(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_byte(soap, tag, i, a, type);
		}
	else
		soap_out_byte(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_byte(struct soap *soap, const char *tag, int id, const char *a, const char *type)
{
	return soap_outbyte(soap, tag, id, a, type, SOAP_TYPE_byte);
}

SOAP_FMAC1 char * SOAP_FMAC2 soap_get_byte(struct soap *soap, char *p, const char *tag, const char *type)
{
	if ((p = soap_in_byte(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 char * SOAP_FMAC2 soap_in_byte(struct soap *soap, const char *tag, char *a, const char *type)
{
	return soap_inbyte(soap, tag, a, type, SOAP_TYPE_byte);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_int(struct soap *soap, int *a)
{
#ifdef SOAP_DEFAULT_int
	*a = SOAP_DEFAULT_int;
#else
	*a = (int)0;
#endif
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_int(struct soap *soap, int const*a)
{
	soap_reference(soap, a, SOAP_TYPE_int);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_int(struct soap *soap, int *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_int, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_int(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_int(soap, tag, i, a, type);
		}
	else
		soap_out_int(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_int(struct soap *soap, const char *tag, int id, const int *a, const char *type)
{
	return soap_outint(soap, tag, id, a, type, SOAP_TYPE_int);
}

SOAP_FMAC1 int * SOAP_FMAC2 soap_get_int(struct soap *soap, int *p, const char *tag, const char *type)
{
	if ((p = soap_in_int(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 int * SOAP_FMAC2 soap_in_int(struct soap *soap, const char *tag, int *a, const char *type)
{
	return soap_inint(soap, tag, a, type, SOAP_TYPE_int);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__boolean(struct soap *soap, enum Enum_ *a)
{
#ifdef SOAP_DEFAULT_xsd__boolean
	*a = SOAP_DEFAULT_xsd__boolean;
#else
	*a = (enum Enum_)0;
#endif
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__boolean(struct soap *soap, enum Enum_ const*a)
{
	soap_reference(soap, a, SOAP_TYPE_xsd__boolean);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__boolean(struct soap *soap, enum Enum_ *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_xsd__boolean, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_xsd__boolean(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_xsd__boolean(soap, tag, i, a, type);
		}
	else
		soap_out_xsd__boolean(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 const char* SOAP_FMAC2 soap_xsd__boolean2s(struct soap *soap, enum Enum_ n)
{	switch (n)
	{
		case false_: return "false";
		case true_: return "true";
	}

	sprintf(soap->tmpbuf, SOAP_LONG_FORMAT, (LONG64)n);
	return soap->tmpbuf;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__boolean(struct soap *soap, const char *tag, int id, const enum Enum_ *a, const char *type)
{	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_xsd__boolean), type);
	soap_send(soap, soap_xsd__boolean2s(soap, *a));
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_get_xsd__boolean(struct soap *soap, enum Enum_ *p, const char *tag, const char *type)
{
	if ((p = soap_in_xsd__boolean(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_s2xsd__boolean(struct soap *soap, const char *s, enum Enum_ *a)
{
	if (!strcmp(s, "false"))
		*a = false_;
	else if (!strcmp(s, "true"))
		*a = true_;
	else 
	{	char *r;
		*a = (enum Enum_)strtol(s, &r, 10);
		if (*r)
			return soap->error = SOAP_TYPE_MISMATCH;
	}
	return SOAP_OK;
}

SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_in_xsd__boolean(struct soap *soap, const char *tag, enum Enum_ *a, const char *type)
{
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
	soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (soap->body && !*soap->href)
	{	a = (enum Enum_ *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_xsd__boolean, sizeof(enum Enum_), 0);
		if (!a || soap_s2xsd__boolean(soap, soap_value(soap), a))
			return NULL;
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (enum Enum_ *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_xsd__boolean, sizeof(enum Enum_), 0), SOAP_TYPE_xsd__boolean, sizeof(enum Enum_));
		if (soap->alloced)
			soap_default_xsd__boolean(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_Enum_(struct soap *soap, enum Enum_ *a)
{
#ifdef SOAP_DEFAULT_Enum_
	*a = SOAP_DEFAULT_Enum_;
#else
	*a = (enum Enum_)0;
#endif
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_Enum_(struct soap *soap, enum Enum_ const*a)
{
	soap_reference(soap, a, SOAP_TYPE_Enum_);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_Enum_(struct soap *soap, enum Enum_ *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_Enum_, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_Enum_(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_Enum_(soap, tag, i, a, type);
		}
	else
		soap_out_Enum_(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 const char* SOAP_FMAC2 soap_Enum_2s(struct soap *soap, enum Enum_ n)
{	switch (n)
	{
		case false_: return "false";
		case true_: return "true";
	}

	sprintf(soap->tmpbuf, SOAP_LONG_FORMAT, (LONG64)n);
	return soap->tmpbuf;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_Enum_(struct soap *soap, const char *tag, int id, const enum Enum_ *a, const char *type)
{	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_Enum_), type);
	soap_send(soap, soap_Enum_2s(soap, *a));
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_get_Enum_(struct soap *soap, enum Enum_ *p, const char *tag, const char *type)
{
	if ((p = soap_in_Enum_(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_s2Enum_(struct soap *soap, const char *s, enum Enum_ *a)
{
	if (!strcmp(s, "false"))
		*a = false_;
	else if (!strcmp(s, "true"))
		*a = true_;
	else 
	{	char *r;
		*a = (enum Enum_)strtol(s, &r, 10);
		if (*r)
			return soap->error = SOAP_TYPE_MISMATCH;
	}
	return SOAP_OK;
}

SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_in_Enum_(struct soap *soap, const char *tag, enum Enum_ *a, const char *type)
{
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
	soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (soap->body && !*soap->href)
	{	a = (enum Enum_ *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_Enum_, sizeof(enum Enum_), 0);
		if (!a || soap_s2Enum_(soap, soap_value(soap), a))
			return NULL;
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (enum Enum_ *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_Enum_, sizeof(enum Enum_), 0), SOAP_TYPE_Enum_, sizeof(enum Enum_));
		if (soap->alloced)
			soap_default_Enum_(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_SOAP_ENV__Fault))
		soap_mark_SOAP_ENV__Fault(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a)
{
	soap_embedded(soap, &a->faultcode, SOAP_TYPE_string);
	soap_mark_string(soap, &a->faultcode);
	soap_embedded(soap, &a->faultstring, SOAP_TYPE_string);
	soap_mark_string(soap, &a->faultstring);
	soap_embedded(soap, &a->faultactor, SOAP_TYPE_string);
	soap_mark_string(soap, &a->faultactor);
	soap_embedded(soap, &a->detail, SOAP_TYPE_string);
	soap_mark_string(soap, &a->detail);
	soap_embedded(soap, &a->SOAP_ENV__Code, SOAP_TYPE_PointerToSOAP_ENV__Code);
	soap_mark_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Code);
	soap_embedded(soap, &a->SOAP_ENV__Reason, SOAP_TYPE_string);
	soap_mark_string(soap, &a->SOAP_ENV__Reason);
	soap_embedded(soap, &a->SOAP_ENV__Detail, SOAP_TYPE_string);
	soap_mark_string(soap, &a->SOAP_ENV__Detail);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *a)
{
	soap_default_string(soap, &a->faultcode);
	soap_default_string(soap, &a->faultstring);
	soap_default_string(soap, &a->faultactor);
	soap_default_string(soap, &a->detail);
	soap_default_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Code);
	soap_default_string(soap, &a->SOAP_ENV__Reason);
	soap_default_string(soap, &a->SOAP_ENV__Detail);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_SOAP_ENV__Fault, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_SOAP_ENV__Fault(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_SOAP_ENV__Fault(soap, tag, i, a, type);
		}
	else
		soap_out_SOAP_ENV__Fault(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Fault(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Fault *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Fault), type);
	soap_out_string(soap, "faultcode", -1, &a->faultcode, "");
	soap_out_string(soap, "faultstring", -1, &a->faultstring, "");
	soap_out_string(soap, "faultactor", -1, &a->faultactor, "");
	soap_out_string(soap, "detail", -1, &a->detail, "");
	soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", -1, &a->SOAP_ENV__Code, "");
	soap_out_string(soap, "SOAP-ENV:Reason", -1, &a->SOAP_ENV__Reason, "");
	soap_out_string(soap, "SOAP-ENV:Detail", -1, &a->SOAP_ENV__Detail, "");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_get_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Fault(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_in_SOAP_ENV__Fault(struct soap *soap, const char *tag, struct SOAP_ENV__Fault *a, const char *type)
{
	short soap_flag_faultcode = 1, soap_flag_faultstring = 1, soap_flag_faultactor = 1, soap_flag_detail = 1, soap_flag_SOAP_ENV__Code = 1, soap_flag_SOAP_ENV__Reason = 1, soap_flag_SOAP_ENV__Detail = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct SOAP_ENV__Fault *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_SOAP_ENV__Fault(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_faultcode && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "faultcode", &a->faultcode, ""))
				{	soap_flag_faultcode = 0;
					continue;
				}
			if (soap_flag_faultstring && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "faultstring", &a->faultstring, ""))
				{	soap_flag_faultstring = 0;
					continue;
				}
			if (soap_flag_faultactor && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "faultactor", &a->faultactor, ""))
				{	soap_flag_faultactor = 0;
					continue;
				}
			if (soap_flag_detail && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "detail", &a->detail, ""))
				{	soap_flag_detail = 0;
					continue;
				}
			if (soap_flag_SOAP_ENV__Code && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", &a->SOAP_ENV__Code, ""))
				{	soap_flag_SOAP_ENV__Code = 0;
					continue;
				}
			if (soap_flag_SOAP_ENV__Reason && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "SOAP-ENV:Reason", &a->SOAP_ENV__Reason, ""))
				{	soap_flag_SOAP_ENV__Reason = 0;
					continue;
				}
			if (soap_flag_SOAP_ENV__Detail && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "SOAP-ENV:Detail", &a->SOAP_ENV__Detail, ""))
				{	soap_flag_SOAP_ENV__Detail = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct SOAP_ENV__Fault *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), 0), SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault));
		if (soap->alloced)
			soap_default_SOAP_ENV__Fault(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_SOAP_ENV__Code))
		soap_mark_SOAP_ENV__Code(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a)
{
	soap_embedded(soap, &a->SOAP_ENV__Value, SOAP_TYPE_string);
	soap_mark_string(soap, &a->SOAP_ENV__Value);
	soap_embedded(soap, &a->SOAP_ENV__Node, SOAP_TYPE_string);
	soap_mark_string(soap, &a->SOAP_ENV__Node);
	soap_embedded(soap, &a->SOAP_ENV__Role, SOAP_TYPE_string);
	soap_mark_string(soap, &a->SOAP_ENV__Role);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *a)
{
	soap_default_string(soap, &a->SOAP_ENV__Value);
	soap_default_string(soap, &a->SOAP_ENV__Node);
	soap_default_string(soap, &a->SOAP_ENV__Role);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_SOAP_ENV__Code, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_SOAP_ENV__Code(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_SOAP_ENV__Code(soap, tag, i, a, type);
		}
	else
		soap_out_SOAP_ENV__Code(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Code(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Code *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Code), type);
	soap_out_string(soap, "SOAP-ENV:Value", -1, &a->SOAP_ENV__Value, "");
	soap_out_string(soap, "SOAP-ENV:Node", -1, &a->SOAP_ENV__Node, "");
	soap_out_string(soap, "SOAP-ENV:Role", -1, &a->SOAP_ENV__Role, "");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_get_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Code(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_in_SOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code *a, const char *type)
{
	short soap_flag_SOAP_ENV__Value = 1, soap_flag_SOAP_ENV__Node = 1, soap_flag_SOAP_ENV__Role = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct SOAP_ENV__Code *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_SOAP_ENV__Code(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Value && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "SOAP-ENV:Value", &a->SOAP_ENV__Value, ""))
				{	soap_flag_SOAP_ENV__Value = 0;
					continue;
				}
			if (soap_flag_SOAP_ENV__Node && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "SOAP-ENV:Node", &a->SOAP_ENV__Node, ""))
				{	soap_flag_SOAP_ENV__Node = 0;
					continue;
				}
			if (soap_flag_SOAP_ENV__Role && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_string(soap, "SOAP-ENV:Role", &a->SOAP_ENV__Role, ""))
				{	soap_flag_SOAP_ENV__Role = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct SOAP_ENV__Code *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0), SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code));
		if (soap->alloced)
			soap_default_SOAP_ENV__Code(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_SOAP_ENV__Header))
		soap_mark_SOAP_ENV__Header(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a)
{
	/* transient dummy skipped */
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *a)
{
	/* transient dummy skipped */
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_SOAP_ENV__Header, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_SOAP_ENV__Header(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_SOAP_ENV__Header(soap, tag, i, a, type);
		}
	else
		soap_out_SOAP_ENV__Header(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Header(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Header *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Header), type);
	/* transient dummy skipped */
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_get_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Header(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_in_SOAP_ENV__Header(struct soap *soap, const char *tag, struct SOAP_ENV__Header *a, const char *type)
{;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct SOAP_ENV__Header *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_SOAP_ENV__Header(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
		/* transient dummy skipped */
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct SOAP_ENV__Header *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), 0), SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header));
		if (soap->alloced)
			soap_default_SOAP_ENV__Header(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__getAttributes(struct soap *soap, struct tns__getAttributes const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_tns__getAttributes))
		soap_mark_tns__getAttributes(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__getAttributes(struct soap *soap, const struct tns__getAttributes *a)
{
	soap_embedded(soap, &a->sessionId, SOAP_TYPE_xsd__string);
	soap_mark_xsd__string(soap, &a->sessionId);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__getAttributes(struct soap *soap, struct tns__getAttributes *a)
{
	soap_default_xsd__string(soap, &a->sessionId);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__getAttributes(struct soap *soap, struct tns__getAttributes *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_tns__getAttributes, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_tns__getAttributes(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_tns__getAttributes(soap, tag, i, a, type);
		}
	else
		soap_out_tns__getAttributes(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__getAttributes(struct soap *soap, const char *tag, int id, const struct tns__getAttributes *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tns__getAttributes), type);
	soap_out_xsd__string(soap, "sessionId", -1, &a->sessionId, "xsd:string");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__getAttributes * SOAP_FMAC2 soap_get_tns__getAttributes(struct soap *soap, struct tns__getAttributes *p, const char *tag, const char *type)
{
	if ((p = soap_in_tns__getAttributes(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__getAttributes * SOAP_FMAC2 soap_in_tns__getAttributes(struct soap *soap, const char *tag, struct tns__getAttributes *a, const char *type)
{
	short soap_flag_sessionId = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct tns__getAttributes *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__getAttributes, sizeof(struct tns__getAttributes), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_tns__getAttributes(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_sessionId && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_xsd__string(soap, "sessionId", &a->sessionId, "xsd:string"))
				{	soap_flag_sessionId = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct tns__getAttributes *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__getAttributes, sizeof(struct tns__getAttributes), 0), SOAP_TYPE_tns__getAttributes, sizeof(struct tns__getAttributes));
		if (soap->alloced)
			soap_default_tns__getAttributes(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__requestSession(struct soap *soap, struct tns__requestSession const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_tns__requestSession))
		soap_mark_tns__requestSession(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__requestSession(struct soap *soap, const struct tns__requestSession *a)
{
	soap_embedded(soap, &a->attributes, SOAP_TYPE_PointerToArrayOfstring);
	soap_mark_PointerToArrayOfstring(soap, &a->attributes);
	soap_embedded(soap, &a->prefix, SOAP_TYPE_xsd__string);
	soap_mark_xsd__string(soap, &a->prefix);
	soap_embedded(soap, &a->postfix, SOAP_TYPE_xsd__string);
	soap_mark_xsd__string(soap, &a->postfix);
	soap_embedded(soap, &a->denySSO, SOAP_TYPE_xsd__boolean);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__requestSession(struct soap *soap, struct tns__requestSession *a)
{
	soap_default_PointerToArrayOfstring(soap, &a->attributes);
	soap_default_xsd__string(soap, &a->prefix);
	soap_default_xsd__string(soap, &a->postfix);
	soap_default_xsd__boolean(soap, &a->denySSO);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__requestSession(struct soap *soap, struct tns__requestSession *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_tns__requestSession, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_tns__requestSession(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_tns__requestSession(soap, tag, i, a, type);
		}
	else
		soap_out_tns__requestSession(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__requestSession(struct soap *soap, const char *tag, int id, const struct tns__requestSession *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tns__requestSession), type);
	soap_out_PointerToArrayOfstring(soap, "attributes", -1, &a->attributes, "xsd:string");
	soap_out_xsd__string(soap, "prefix", -1, &a->prefix, "xsd:string");
	soap_out_xsd__string(soap, "postfix", -1, &a->postfix, "xsd:string");
	soap_out_xsd__boolean(soap, "denySSO", -1, &a->denySSO, "xsd:boolean");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__requestSession * SOAP_FMAC2 soap_get_tns__requestSession(struct soap *soap, struct tns__requestSession *p, const char *tag, const char *type)
{
	if ((p = soap_in_tns__requestSession(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__requestSession * SOAP_FMAC2 soap_in_tns__requestSession(struct soap *soap, const char *tag, struct tns__requestSession *a, const char *type)
{
	short soap_flag_attributes = 1, soap_flag_prefix = 1, soap_flag_postfix = 1, soap_flag_denySSO = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct tns__requestSession *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__requestSession, sizeof(struct tns__requestSession), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_tns__requestSession(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_attributes && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToArrayOfstring(soap, "attributes", &a->attributes, "xsd:string"))
				{	soap_flag_attributes = 0;
					continue;
				}
			if (soap_flag_prefix && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_xsd__string(soap, "prefix", &a->prefix, "xsd:string"))
				{	soap_flag_prefix = 0;
					continue;
				}
			if (soap_flag_postfix && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_xsd__string(soap, "postfix", &a->postfix, "xsd:string"))
				{	soap_flag_postfix = 0;
					continue;
				}
			if (soap_flag_denySSO && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_xsd__boolean(soap, "denySSO", &a->denySSO, "xsd:boolean"))
				{	soap_flag_denySSO = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct tns__requestSession *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__requestSession, sizeof(struct tns__requestSession), 0), SOAP_TYPE_tns__requestSession, sizeof(struct tns__requestSession));
		if (soap->alloced)
			soap_default_tns__requestSession(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Attribute(struct soap *soap, struct tns__Attribute const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_tns__Attribute))
		soap_mark_tns__Attribute(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Attribute(struct soap *soap, const struct tns__Attribute *a)
{
	soap_embedded(soap, &a->name, SOAP_TYPE_xsd__string);
	soap_mark_xsd__string(soap, &a->name);
	soap_embedded(soap, &a->values, SOAP_TYPE_PointerToArrayOfstring);
	soap_mark_PointerToArrayOfstring(soap, &a->values);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Attribute(struct soap *soap, struct tns__Attribute *a)
{
	soap_default_xsd__string(soap, &a->name);
	soap_default_PointerToArrayOfstring(soap, &a->values);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Attribute(struct soap *soap, struct tns__Attribute *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_tns__Attribute, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_tns__Attribute(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_tns__Attribute(soap, tag, i, a, type);
		}
	else
		soap_out_tns__Attribute(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Attribute(struct soap *soap, const char *tag, int id, const struct tns__Attribute *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tns__Attribute), type);
	soap_out_xsd__string(soap, "name", -1, &a->name, "xsd:string");
	soap_out_PointerToArrayOfstring(soap, "values", -1, &a->values, "xsd:string");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__Attribute * SOAP_FMAC2 soap_get_tns__Attribute(struct soap *soap, struct tns__Attribute *p, const char *tag, const char *type)
{
	if ((p = soap_in_tns__Attribute(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__Attribute * SOAP_FMAC2 soap_in_tns__Attribute(struct soap *soap, const char *tag, struct tns__Attribute *a, const char *type)
{
	short soap_flag_name = 1, soap_flag_values = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct tns__Attribute *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__Attribute, sizeof(struct tns__Attribute), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_tns__Attribute(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_name && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_xsd__string(soap, "name", &a->name, "xsd:string"))
				{	soap_flag_name = 0;
					continue;
				}
			if (soap_flag_values && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToArrayOfstring(soap, "values", &a->values, "xsd:string"))
				{	soap_flag_values = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct tns__Attribute *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__Attribute, sizeof(struct tns__Attribute), 0), SOAP_TYPE_tns__Attribute, sizeof(struct tns__Attribute));
		if (soap->alloced)
			soap_default_tns__Attribute(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_tns__requestSessionResponse))
		soap_mark_tns__requestSessionResponse(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__requestSessionResponse(struct soap *soap, const struct tns__requestSessionResponse *a)
{
	soap_embedded(soap, &a->_result, SOAP_TYPE_xsd__string);
	soap_mark_xsd__string(soap, &a->_result);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse *a)
{
	soap_default_xsd__string(soap, &a->_result);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_tns__requestSessionResponse, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_tns__requestSessionResponse(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_tns__requestSessionResponse(soap, tag, i, a, type);
		}
	else
		soap_out_tns__requestSessionResponse(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__requestSessionResponse(struct soap *soap, const char *tag, int id, const struct tns__requestSessionResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tns__requestSessionResponse), type);
	soap_out_xsd__string(soap, "result", -1, &a->_result, "xsd:string");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__requestSessionResponse * SOAP_FMAC2 soap_get_tns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_tns__requestSessionResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__requestSessionResponse * SOAP_FMAC2 soap_in_tns__requestSessionResponse(struct soap *soap, const char *tag, struct tns__requestSessionResponse *a, const char *type)
{
	short soap_flag__result = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct tns__requestSessionResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__requestSessionResponse, sizeof(struct tns__requestSessionResponse), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_tns__requestSessionResponse(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag__result && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_xsd__string(soap, NULL, &a->_result, "xsd:string"))
				{	soap_flag__result = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct tns__requestSessionResponse *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__requestSessionResponse, sizeof(struct tns__requestSessionResponse), 0), SOAP_TYPE_tns__requestSessionResponse, sizeof(struct tns__requestSessionResponse));
		if (soap->alloced)
			soap_default_tns__requestSessionResponse(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_ArrayOfstring(struct soap *soap, struct ArrayOfstring const*a)
{
	soap_mark_ArrayOfstring(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_ArrayOfstring(struct soap *soap, struct ArrayOfstring const*a)
{
	int i;
	if (a->__ptr && !soap_array_reference(soap, a, (struct soap_array*)&a->__ptr, a->__size, SOAP_TYPE_ArrayOfstring))
		for (i = 0; i < a->__size; i++)
		{	soap_embedded(soap, a->__ptr + i, SOAP_TYPE_xsd__string);
			soap_mark_xsd__string(soap, a->__ptr + i);
		}
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_ArrayOfstring(struct soap *soap, struct ArrayOfstring *a)
{
	a->__size = 0;
	a->__ptr = NULL;
	a->__offset = 0;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_ArrayOfstring(struct soap *soap, struct ArrayOfstring *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_array_pointer_lookup(soap, a, (struct soap_array*)&a->__ptr, a->__size, SOAP_TYPE_ArrayOfstring, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_ArrayOfstring(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_ArrayOfstring(soap, tag, i, a, type);
		}
	else
		soap_out_ArrayOfstring(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_ArrayOfstring(struct soap *soap, const char *tag, int id, const struct ArrayOfstring *a, const char *type)
{
	int i;
	struct soap_plist *pp;
	int n = a->__size;
	char *t = soap_putsize(soap, type, n + a->__offset);
	i = soap_array_pointer_lookup(soap, a, (struct soap_array*)&a->__ptr, n, SOAP_TYPE_ArrayOfstring, &pp);
	if (!a->__ptr)
	{	soap_element_null(soap, tag, i, t);
		return SOAP_OK;
	}
	if (id <= 0 && i)
	{	if (soap_is_embedded(soap, pp))
		{	soap_element_ref(soap, tag, 0, i);
			return SOAP_OK;
		}
		if (soap_is_single(soap, pp))
			i = 0;
	}
	else if (id > 0)
		i = id;
	soap_array_begin_out(soap, tag, i, t, soap_putoffset(soap, a->__offset));
	if (i)
		soap_set_embedded(soap, pp);
	for (i = 0; i < n; i++)
	{
		soap->position = 1;
		soap->positions[0] = i;
		soap_out_xsd__string(soap, "item", 0, &a->__ptr[i], "xsd:string");
	}
	soap->position = 0;
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct ArrayOfstring * SOAP_FMAC2 soap_get_ArrayOfstring(struct soap *soap, struct ArrayOfstring *p, const char *tag, const char *type)
{
	if ((p = soap_in_ArrayOfstring(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct ArrayOfstring * SOAP_FMAC2 soap_in_ArrayOfstring(struct soap *soap, const char *tag, struct ArrayOfstring *a, const char *type)
{	int i, j;
	char **p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap_match_array(soap, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if ((a = (struct ArrayOfstring *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ArrayOfstring, sizeof(struct ArrayOfstring), 0)))
			soap_default_ArrayOfstring(soap, a);
			if (soap->body && soap_element_end_in(soap, tag))
				return NULL;
	}
	else if (!*soap->href)
	{	if (!(a = (struct ArrayOfstring *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ArrayOfstring, sizeof(struct ArrayOfstring), 0)))
			return NULL;
		if (soap->alloced)
			soap_default_ArrayOfstring(soap, a);
		if (soap->body)
		{
		a->__size = soap_getsize(soap->arraySize, soap->arrayOffset, &j);
		a->__offset = j;
		if (j >= 0 && a->__size >= 0)
		{	a->__ptr = (char **)soap_malloc(soap, sizeof(char *) * a->__size);
			for (i = 0; i < a->__size; i++)
				soap_default_xsd__string(soap, a->__ptr+i);
			for (i = 0; i < a->__size; i++)
			{	soap_peek_element(soap);
				if (soap->position)
				{	i = soap->positions[0]-j;
					if (i < 0 || i >= a->__size)
					{	soap->error = SOAP_IOB;
					return NULL;
					}
				}
				if (!soap_in_xsd__string(soap, NULL, a->__ptr+i, "xsd:string"))
				{	if (soap->error == SOAP_NO_TAG)
					{	soap->error = SOAP_OK;
						break;
					}
					else
						return NULL;
				}
			}
		}
		else
		{	soap_new_block(soap);
			for (a->__size = 0; ; a->__size++)
			{	p = (char **)soap_push_block(soap, sizeof(char *));
				if (!p)
					return NULL;
				soap_default_xsd__string(soap, p);
				if (!soap_in_xsd__string(soap, NULL, p, "xsd:string"))
				{	if (soap->error == SOAP_NO_TAG)
					{	soap->error = SOAP_OK;
						break;
					}
					else
						return NULL;
				}
			}
			soap_pop_block(soap);
			a->__ptr = (char **)soap_malloc(soap, soap->blist->size);
			soap_store_block(soap, (char*)a->__ptr);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct ArrayOfstring *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ArrayOfstring, sizeof(struct ArrayOfstring), 0), SOAP_TYPE_ArrayOfstring, sizeof(struct ArrayOfstring));
		if (soap->alloced)
			soap_default_ArrayOfstring(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
		return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_tns__getAttributesResponse))
		soap_mark_tns__getAttributesResponse(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__getAttributesResponse(struct soap *soap, const struct tns__getAttributesResponse *a)
{
	soap_embedded(soap, &a->_result, SOAP_TYPE_PointerToArrayOfAttribute);
	soap_mark_PointerToArrayOfAttribute(soap, &a->_result);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse *a)
{
	soap_default_PointerToArrayOfAttribute(soap, &a->_result);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_tns__getAttributesResponse, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_tns__getAttributesResponse(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_tns__getAttributesResponse(soap, tag, i, a, type);
		}
	else
		soap_out_tns__getAttributesResponse(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__getAttributesResponse(struct soap *soap, const char *tag, int id, const struct tns__getAttributesResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tns__getAttributesResponse), type);
	soap_out_PointerToArrayOfAttribute(soap, "result", -1, &a->_result, "tns:Attribute");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__getAttributesResponse * SOAP_FMAC2 soap_get_tns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_tns__getAttributesResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__getAttributesResponse * SOAP_FMAC2 soap_in_tns__getAttributesResponse(struct soap *soap, const char *tag, struct tns__getAttributesResponse *a, const char *type)
{
	short soap_flag__result = 1;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if (soap->mode & SOAP_XML_NIL)
		{	soap->error = SOAP_NULL;
			return NULL;
		}
		else
			return a;
	}
	if (!*soap->href)
	{	a = (struct tns__getAttributesResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__getAttributesResponse, sizeof(struct tns__getAttributesResponse), 0);
		if (!a)
			return NULL;
		if (soap->alloced)
			soap_default_tns__getAttributesResponse(soap, a);
		if (soap->body)
		{	for (;;)
			{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag__result && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToArrayOfAttribute(soap, NULL, &a->_result, "tns:Attribute"))
				{	soap_flag__result = 0;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
			{	return NULL;
			}
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct tns__getAttributesResponse *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tns__getAttributesResponse, sizeof(struct tns__getAttributesResponse), 0), SOAP_TYPE_tns__getAttributesResponse, sizeof(struct tns__getAttributesResponse));
		if (soap->alloced)
			soap_default_tns__getAttributesResponse(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_ArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute const*a)
{
	soap_mark_ArrayOfAttribute(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_ArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute const*a)
{
	int i;
	if (a->__ptr && !soap_array_reference(soap, a, (struct soap_array*)&a->__ptr, a->__size, SOAP_TYPE_ArrayOfAttribute))
		for (i = 0; i < a->__size; i++)
		{	soap_embedded(soap, a->__ptr + i, SOAP_TYPE_tns__Attribute);
			soap_mark_tns__Attribute(soap, a->__ptr + i);
		}
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_ArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute *a)
{
	a->__size = 0;
	a->__ptr = NULL;
	a->__offset = 0;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_ArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute *a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_array_pointer_lookup(soap, a, (struct soap_array*)&a->__ptr, a->__size, SOAP_TYPE_ArrayOfAttribute, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_ArrayOfAttribute(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_ArrayOfAttribute(soap, tag, i, a, type);
		}
	else
		soap_out_ArrayOfAttribute(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_ArrayOfAttribute(struct soap *soap, const char *tag, int id, const struct ArrayOfAttribute *a, const char *type)
{
	int i;
	struct soap_plist *pp;
	int n = a->__size;
	char *t = soap_putsize(soap, type, n + a->__offset);
	i = soap_array_pointer_lookup(soap, a, (struct soap_array*)&a->__ptr, n, SOAP_TYPE_ArrayOfAttribute, &pp);
	if (!a->__ptr)
	{	soap_element_null(soap, tag, i, t);
		return SOAP_OK;
	}
	if (id <= 0 && i)
	{	if (soap_is_embedded(soap, pp))
		{	soap_element_ref(soap, tag, 0, i);
			return SOAP_OK;
		}
		if (soap_is_single(soap, pp))
			i = 0;
	}
	else if (id > 0)
		i = id;
	soap_array_begin_out(soap, tag, i, t, soap_putoffset(soap, a->__offset));
	if (i)
		soap_set_embedded(soap, pp);
	for (i = 0; i < n; i++)
	{
		soap_out_tns__Attribute(soap, "item", 0, &a->__ptr[i], "tns:Attribute");
	}
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC1 struct ArrayOfAttribute * SOAP_FMAC2 soap_get_ArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute *p, const char *tag, const char *type)
{
	if ((p = soap_in_ArrayOfAttribute(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct ArrayOfAttribute * SOAP_FMAC2 soap_in_ArrayOfAttribute(struct soap *soap, const char *tag, struct ArrayOfAttribute *a, const char *type)
{	int i, j;
	struct tns__Attribute *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap_match_array(soap, type))
	{	soap->error = SOAP_TYPE_MISMATCH;
		soap_revert(soap);
		return NULL;
	}
	if (soap->null)
	{	if ((a = (struct ArrayOfAttribute *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ArrayOfAttribute, sizeof(struct ArrayOfAttribute), 0)))
			soap_default_ArrayOfAttribute(soap, a);
			if (soap->body && soap_element_end_in(soap, tag))
				return NULL;
	}
	else if (!*soap->href)
	{	if (!(a = (struct ArrayOfAttribute *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ArrayOfAttribute, sizeof(struct ArrayOfAttribute), 0)))
			return NULL;
		if (soap->alloced)
			soap_default_ArrayOfAttribute(soap, a);
		if (soap->body)
		{
		a->__size = soap_getsize(soap->arraySize, soap->arrayOffset, &j);
		a->__offset = j;
		if (j >= 0 && a->__size >= 0)
		{	a->__ptr = (struct tns__Attribute *)soap_malloc(soap, sizeof(struct tns__Attribute) * a->__size);
			for (i = 0; i < a->__size; i++)
				soap_default_tns__Attribute(soap, a->__ptr+i);
			for (i = 0; i < a->__size; i++)
			{	soap_peek_element(soap);
				if (soap->position)
				{	i = soap->positions[0]-j;
					if (i < 0 || i >= a->__size)
					{	soap->error = SOAP_IOB;
					return NULL;
					}
				}
				if (!soap_in_tns__Attribute(soap, NULL, a->__ptr+i, "tns:Attribute"))
				{	if (soap->error == SOAP_NO_TAG)
					{	soap->error = SOAP_OK;
						break;
					}
					else
						return NULL;
				}
			}
		}
		else
		{	soap_new_block(soap);
			for (a->__size = 0; ; a->__size++)
			{	p = (struct tns__Attribute *)soap_push_block(soap, sizeof(struct tns__Attribute));
				if (!p)
					return NULL;
				soap_default_tns__Attribute(soap, p);
				if (!soap_in_tns__Attribute(soap, NULL, p, "tns:Attribute"))
				{	if (soap->error == SOAP_NO_TAG)
					{	soap->error = SOAP_OK;
						break;
					}
					else
						return NULL;
				}
			}
			soap_pop_block(soap);
			a->__ptr = (struct tns__Attribute *)soap_malloc(soap, soap->blist->size);
			soap_store_block(soap, (char*)a->__ptr);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		}
	}
	else
	{	a = (struct ArrayOfAttribute *)soap_id_forward(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ArrayOfAttribute, sizeof(struct ArrayOfAttribute), 0), SOAP_TYPE_ArrayOfAttribute, sizeof(struct ArrayOfAttribute));
		if (soap->alloced)
			soap_default_ArrayOfAttribute(soap, a);
		if (soap->body && soap_element_end_in(soap, tag))
		return NULL;
	}
	return a;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerToSOAP_ENV__Code))
		soap_mark_PointerToSOAP_ENV__Code(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Code))
		soap_mark_SOAP_ENV__Code(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code **a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerToSOAP_ENV__Code, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerToSOAP_ENV__Code(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerToSOAP_ENV__Code(soap, tag, i, a, type);
		}
	else
		soap_out_PointerToSOAP_ENV__Code(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Code *const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerToSOAP_ENV__Code);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_pointer_lookup(soap, *a, SOAP_TYPE_SOAP_ENV__Code, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_SOAP_ENV__Code(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_SOAP_ENV__Code(soap, tag, i, *a, type);
			}
		else
			soap_out_SOAP_ENV__Code(soap, tag, soap_pointer_enter(soap, *a, SOAP_TYPE_SOAP_ENV__Code, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_get_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Code(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_in_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code **a, const char *type)
{
	struct SOAP_ENV__Code *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (struct SOAP_ENV__Code **)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToSOAP_ENV__Code, sizeof(struct SOAP_ENV__Code *), 1);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_SOAP_ENV__Code(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_SOAP_ENV__Code(soap, tag, NULL, type)))
		{	a = (struct SOAP_ENV__Code **)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerToSOAP_ENV__Code, sizeof(struct SOAP_ENV__Code *), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (struct SOAP_ENV__Code **)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToSOAP_ENV__Code, sizeof(struct SOAP_ENV__Code *), 1), SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse *const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerTotns__getAttributesResponse))
		soap_mark_PointerTotns__getAttributesResponse(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_tns__getAttributesResponse))
		soap_mark_tns__getAttributesResponse(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse **a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerTotns__getAttributesResponse, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerTotns__getAttributesResponse(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerTotns__getAttributesResponse(soap, tag, i, a, type);
		}
	else
		soap_out_PointerTotns__getAttributesResponse(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__getAttributesResponse(struct soap *soap, const char *tag, int id, struct tns__getAttributesResponse *const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerTotns__getAttributesResponse);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_pointer_lookup(soap, *a, SOAP_TYPE_tns__getAttributesResponse, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_tns__getAttributesResponse(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_tns__getAttributesResponse(soap, tag, i, *a, type);
			}
		else
			soap_out_tns__getAttributesResponse(soap, tag, soap_pointer_enter(soap, *a, SOAP_TYPE_tns__getAttributesResponse, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__getAttributesResponse ** SOAP_FMAC2 soap_get_PointerTotns__getAttributesResponse(struct soap *soap, struct tns__getAttributesResponse **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTotns__getAttributesResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__getAttributesResponse ** SOAP_FMAC2 soap_in_PointerTotns__getAttributesResponse(struct soap *soap, const char *tag, struct tns__getAttributesResponse **a, const char *type)
{
	struct tns__getAttributesResponse *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (struct tns__getAttributesResponse **)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerTotns__getAttributesResponse, sizeof(struct tns__getAttributesResponse *), 1);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_tns__getAttributesResponse(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_tns__getAttributesResponse(soap, tag, NULL, type)))
		{	a = (struct tns__getAttributesResponse **)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerTotns__getAttributesResponse, sizeof(struct tns__getAttributesResponse *), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (struct tns__getAttributesResponse **)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerTotns__getAttributesResponse, sizeof(struct tns__getAttributesResponse *), 1), SOAP_TYPE_tns__getAttributesResponse, sizeof(struct tns__getAttributesResponse), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse *const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerTotns__requestSessionResponse))
		soap_mark_PointerTotns__requestSessionResponse(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_tns__requestSessionResponse))
		soap_mark_tns__requestSessionResponse(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse **a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerTotns__requestSessionResponse, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerTotns__requestSessionResponse(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerTotns__requestSessionResponse(soap, tag, i, a, type);
		}
	else
		soap_out_PointerTotns__requestSessionResponse(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__requestSessionResponse(struct soap *soap, const char *tag, int id, struct tns__requestSessionResponse *const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerTotns__requestSessionResponse);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_pointer_lookup(soap, *a, SOAP_TYPE_tns__requestSessionResponse, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_tns__requestSessionResponse(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_tns__requestSessionResponse(soap, tag, i, *a, type);
			}
		else
			soap_out_tns__requestSessionResponse(soap, tag, soap_pointer_enter(soap, *a, SOAP_TYPE_tns__requestSessionResponse, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__requestSessionResponse ** SOAP_FMAC2 soap_get_PointerTotns__requestSessionResponse(struct soap *soap, struct tns__requestSessionResponse **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTotns__requestSessionResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__requestSessionResponse ** SOAP_FMAC2 soap_in_PointerTotns__requestSessionResponse(struct soap *soap, const char *tag, struct tns__requestSessionResponse **a, const char *type)
{
	struct tns__requestSessionResponse *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (struct tns__requestSessionResponse **)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerTotns__requestSessionResponse, sizeof(struct tns__requestSessionResponse *), 1);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_tns__requestSessionResponse(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_tns__requestSessionResponse(soap, tag, NULL, type)))
		{	a = (struct tns__requestSessionResponse **)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerTotns__requestSessionResponse, sizeof(struct tns__requestSessionResponse *), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (struct tns__requestSessionResponse **)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerTotns__requestSessionResponse, sizeof(struct tns__requestSessionResponse *), 1), SOAP_TYPE_tns__requestSessionResponse, sizeof(struct tns__requestSessionResponse), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__Attribute(struct soap *soap, struct tns__Attribute *const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerTotns__Attribute))
		soap_mark_PointerTotns__Attribute(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__Attribute(struct soap *soap, struct tns__Attribute *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_tns__Attribute))
		soap_mark_tns__Attribute(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__Attribute(struct soap *soap, struct tns__Attribute **a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__Attribute(struct soap *soap, struct tns__Attribute **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerTotns__Attribute, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerTotns__Attribute(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerTotns__Attribute(soap, tag, i, a, type);
		}
	else
		soap_out_PointerTotns__Attribute(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__Attribute(struct soap *soap, const char *tag, int id, struct tns__Attribute *const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerTotns__Attribute);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_pointer_lookup(soap, *a, SOAP_TYPE_tns__Attribute, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_tns__Attribute(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_tns__Attribute(soap, tag, i, *a, type);
			}
		else
			soap_out_tns__Attribute(soap, tag, soap_pointer_enter(soap, *a, SOAP_TYPE_tns__Attribute, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 struct tns__Attribute ** SOAP_FMAC2 soap_get_PointerTotns__Attribute(struct soap *soap, struct tns__Attribute **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTotns__Attribute(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct tns__Attribute ** SOAP_FMAC2 soap_in_PointerTotns__Attribute(struct soap *soap, const char *tag, struct tns__Attribute **a, const char *type)
{
	struct tns__Attribute *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (struct tns__Attribute **)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerTotns__Attribute, sizeof(struct tns__Attribute *), 1);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_tns__Attribute(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_tns__Attribute(soap, tag, NULL, type)))
		{	a = (struct tns__Attribute **)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerTotns__Attribute, sizeof(struct tns__Attribute *), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (struct tns__Attribute **)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerTotns__Attribute, sizeof(struct tns__Attribute *), 1), SOAP_TYPE_tns__Attribute, sizeof(struct tns__Attribute), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToArrayOfstring(struct soap *soap, struct ArrayOfstring *const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerToArrayOfstring))
		soap_mark_PointerToArrayOfstring(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToArrayOfstring(struct soap *soap, struct ArrayOfstring *const*a)
{
	if (*a && !soap_array_reference(soap, *a, (struct soap_array*)&(*a)->__ptr, (*a)->__size, SOAP_TYPE_ArrayOfstring))
		soap_mark_ArrayOfstring(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToArrayOfstring(struct soap *soap, struct ArrayOfstring **a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToArrayOfstring(struct soap *soap, struct ArrayOfstring **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerToArrayOfstring, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerToArrayOfstring(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerToArrayOfstring(soap, tag, i, a, type);
		}
	else
		soap_out_PointerToArrayOfstring(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToArrayOfstring(struct soap *soap, const char *tag, int id, struct ArrayOfstring *const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerToArrayOfstring);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_array_pointer_lookup(soap, *a, (struct soap_array*)&(*a)->__ptr, (*a)->__size, SOAP_TYPE_ArrayOfstring, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_ArrayOfstring(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_ArrayOfstring(soap, tag, i, *a, type);
			}
		else
			soap_out_ArrayOfstring(soap, tag, soap_array_pointer_enter(soap, *a, (struct soap_array*)&(*a)->__ptr, SOAP_TYPE_ArrayOfstring, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 struct ArrayOfstring ** SOAP_FMAC2 soap_get_PointerToArrayOfstring(struct soap *soap, struct ArrayOfstring **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToArrayOfstring(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct ArrayOfstring ** SOAP_FMAC2 soap_in_PointerToArrayOfstring(struct soap *soap, const char *tag, struct ArrayOfstring **a, const char *type)
{
	struct ArrayOfstring *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (struct ArrayOfstring **)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToArrayOfstring, sizeof(struct ArrayOfstring *), 1);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_ArrayOfstring(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_ArrayOfstring(soap, tag, NULL, type)))
		{	a = (struct ArrayOfstring **)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerToArrayOfstring, sizeof(struct ArrayOfstring *), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (struct ArrayOfstring **)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToArrayOfstring, sizeof(struct ArrayOfstring *), 1), SOAP_TYPE_ArrayOfstring, sizeof(struct ArrayOfstring), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToxsd__string(struct soap *soap, char **const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerToxsd__string))
		soap_mark_PointerToxsd__string(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToxsd__string(struct soap *soap, char **const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_xsd__string))
		soap_mark_xsd__string(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToxsd__string(struct soap *soap, char ***a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToxsd__string(struct soap *soap, char ***a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerToxsd__string, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerToxsd__string(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerToxsd__string(soap, tag, i, a, type);
		}
	else
		soap_out_PointerToxsd__string(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToxsd__string(struct soap *soap, const char *tag, int id, char **const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerToxsd__string);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_pointer_lookup(soap, *a, SOAP_TYPE_xsd__string, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_xsd__string(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_xsd__string(soap, tag, i, *a, type);
			}
		else
			soap_out_xsd__string(soap, tag, soap_pointer_enter(soap, *a, SOAP_TYPE_xsd__string, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 char *** SOAP_FMAC2 soap_get_PointerToxsd__string(struct soap *soap, char ***p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToxsd__string(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 char *** SOAP_FMAC2 soap_in_PointerToxsd__string(struct soap *soap, const char *tag, char ***a, const char *type)
{
	char **p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (char ***)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToxsd__string, sizeof(char **), 2);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_xsd__string(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_xsd__string(soap, tag, NULL, type)))
		{	a = (char ***)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerToxsd__string, sizeof(char **), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (char ***)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToxsd__string, sizeof(char **), 2), SOAP_TYPE_xsd__string, sizeof(char *), 1);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute *const*a)
{
	if (!soap_reference(soap, a, SOAP_TYPE_PointerToArrayOfAttribute))
		soap_mark_PointerToArrayOfAttribute(soap, a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute *const*a)
{
	if (*a && !soap_array_reference(soap, *a, (struct soap_array*)&(*a)->__ptr, (*a)->__size, SOAP_TYPE_ArrayOfAttribute))
		soap_mark_ArrayOfAttribute(soap, *a);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute **a)
{
	*a = NULL;
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_PointerToArrayOfAttribute, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_PointerToArrayOfAttribute(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_PointerToArrayOfAttribute(soap, tag, i, a, type);
		}
	else
		soap_out_PointerToArrayOfAttribute(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToArrayOfAttribute(struct soap *soap, const char *tag, int id, struct ArrayOfAttribute *const*a, const char *type)
{
	id = soap_embedded_id(soap, id, a, SOAP_TYPE_PointerToArrayOfAttribute);
	if (!*a)
		soap_element_null(soap, tag, id, type);
	else
	{	struct soap_plist *pp;
		int i = soap_array_pointer_lookup(soap, *a, (struct soap_array*)&(*a)->__ptr, (*a)->__size, SOAP_TYPE_ArrayOfAttribute, &pp);
		if (i)
			if (soap_is_embedded(soap, pp))
				soap_element_ref(soap, tag, id, i);
			else if (soap_is_single(soap, pp))
				soap_out_ArrayOfAttribute(soap, tag, 0, *a, type);
			else
			{	soap_set_embedded(soap, pp);
				soap_out_ArrayOfAttribute(soap, tag, i, *a, type);
			}
		else
			soap_out_ArrayOfAttribute(soap, tag, soap_array_pointer_enter(soap, *a, (struct soap_array*)&(*a)->__ptr, SOAP_TYPE_ArrayOfAttribute, &pp), *a, type);
	}
	return SOAP_OK;
}

SOAP_FMAC1 struct ArrayOfAttribute ** SOAP_FMAC2 soap_get_PointerToArrayOfAttribute(struct soap *soap, struct ArrayOfAttribute **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToArrayOfAttribute(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 struct ArrayOfAttribute ** SOAP_FMAC2 soap_in_PointerToArrayOfAttribute(struct soap *soap, const char *tag, struct ArrayOfAttribute **a, const char *type)
{
	struct ArrayOfAttribute *p;
	if (soap_element_begin_in(soap, tag))
		return NULL;
	if (soap->null)
	{	a = (struct ArrayOfAttribute **)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToArrayOfAttribute, sizeof(struct ArrayOfAttribute *), 1);
		if (a)
			*a = NULL;
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	else if (!*soap->href)
	{	soap_revert(soap);
		if (a)
		{	if ((p = soap_in_ArrayOfAttribute(soap, tag, *a, type)))
				*a = p;
			else
				a = NULL;
		}
		else if ((p = soap_in_ArrayOfAttribute(soap, tag, NULL, type)))
		{	a = (struct ArrayOfAttribute **)soap_id_enter(soap, "", NULL, SOAP_TYPE_PointerToArrayOfAttribute, sizeof(struct ArrayOfAttribute *), 0);
			if (a)
				*a = p;
		}
	}
	else
	{	a = (struct ArrayOfAttribute **)soap_id_lookup(soap, soap->href, (void**)soap_id_enter(soap, soap->id, a, SOAP_TYPE_PointerToArrayOfAttribute, sizeof(struct ArrayOfAttribute *), 1), SOAP_TYPE_ArrayOfAttribute, sizeof(struct ArrayOfAttribute), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__string(struct soap *soap, char **a)
{
#ifdef SOAP_DEFAULT_xsd__string
	*a = SOAP_DEFAULT_xsd__string;
#else
	*a = (char *)0;
#endif
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__string(struct soap *soap, char *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_xsd__string);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsd__string(struct soap *soap, char *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_xsd__string);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__string(struct soap *soap, char **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_xsd__string, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_xsd__string(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_xsd__string(soap, tag, i, a, type);
		}
	else
		soap_out_xsd__string(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__string(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_xsd__string);
}

SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsd__string(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in_xsd__string(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsd__string(struct soap *soap, const char *tag, char **a, const char *type)
{
	return soap_instring(soap, tag, a, type, SOAP_TYPE_xsd__string, 1);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_default_string(struct soap *soap, char **a)
{
#ifdef SOAP_DEFAULT_string
	*a = SOAP_DEFAULT_string;
#else
	*a = (char *)0;
#endif
}

SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_string(struct soap *soap, char *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_string);
}

SOAP_FMAC1 void SOAP_FMAC2 soap_mark_string(struct soap *soap, char *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_string);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_put_string(struct soap *soap, char **a, const char *tag, const char *type)
{
	int i;
	struct soap_plist *pp;
	if ((i = soap_pointer_lookup(soap, a, SOAP_TYPE_string, &pp)))
		if (soap_is_embedded(soap, pp))
			soap_element_ref(soap, tag, 0, i);
		else if (soap_is_single(soap, pp))
			soap_out_string(soap, tag, 0, a, type);
		else
		{
			soap_set_embedded(soap, pp);
			soap_out_string(soap, tag, i, a, type);
		}
	else
		soap_out_string(soap, tag, 0, a, type);
	return soap_putindependent(soap);
}

SOAP_FMAC1 int SOAP_FMAC2 soap_out_string(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_string);
}

SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_string(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in_string(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_string(struct soap *soap, const char *tag, char **a, const char *type)
{
	return soap_instring(soap, tag, a, type, SOAP_TYPE_string, 1);
}

/* end of soapC.cpp */
