/* soapH.h
   Generated by gSOAP 2.2.3b from Authentication.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef soapH_H
#define soapH_H
#include "stdsoap2.h"
#include "soapStub.h"

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (1)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_byte(struct soap*, char *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (2)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_int(struct soap*, int *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (3)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__boolean(struct soap*, enum Enum_ *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__boolean(struct soap*, enum Enum_ const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__boolean(struct soap*, enum Enum_ *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__boolean(struct soap*, const char*, int, const enum Enum_ *, const char*);

SOAP_FMAC1 const char* SOAP_FMAC2 soap_xsd__boolean2s(struct soap*, enum Enum_);
SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_get_xsd__boolean(struct soap*, enum Enum_ *, const char*, const char*);
SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_in_xsd__boolean(struct soap*, const char*, enum Enum_ *, const char*);

SOAP_FMAC1 int SOAP_FMAC2 soap_s2xsd__boolean(struct soap*, const char*, enum Enum_ *);

#ifndef SOAP_TYPE_Enum_
#define SOAP_TYPE_Enum_ (4)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_Enum_(struct soap*, enum Enum_ *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_Enum_(struct soap*, enum Enum_ const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_Enum_(struct soap*, enum Enum_ *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_Enum_(struct soap*, const char*, int, const enum Enum_ *, const char*);

SOAP_FMAC1 const char* SOAP_FMAC2 soap_Enum_2s(struct soap*, enum Enum_);
SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_get_Enum_(struct soap*, enum Enum_ *, const char*, const char*);
SOAP_FMAC1 enum Enum_ * SOAP_FMAC2 soap_in_Enum_(struct soap*, const char*, enum Enum_ *, const char*);

SOAP_FMAC1 int SOAP_FMAC2 soap_s2Enum_(struct soap*, const char*, enum Enum_ *);

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (5)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (6)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (7)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef SOAP_TYPE_tns__getAttributes
#define SOAP_TYPE_tns__getAttributes (8)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__getAttributes(struct soap*, struct tns__getAttributes const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__getAttributes(struct soap*, const struct tns__getAttributes *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__getAttributes(struct soap*, struct tns__getAttributes *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__getAttributes(struct soap*, struct tns__getAttributes *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__getAttributes(struct soap*, const char*, int, const struct tns__getAttributes *, const char*);
SOAP_FMAC1 struct tns__getAttributes * SOAP_FMAC2 soap_get_tns__getAttributes(struct soap*, struct tns__getAttributes *, const char*, const char*);
SOAP_FMAC1 struct tns__getAttributes * SOAP_FMAC2 soap_in_tns__getAttributes(struct soap*, const char*, struct tns__getAttributes *, const char*);

#ifndef SOAP_TYPE_tns__requestSession
#define SOAP_TYPE_tns__requestSession (9)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__requestSession(struct soap*, struct tns__requestSession const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__requestSession(struct soap*, const struct tns__requestSession *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__requestSession(struct soap*, struct tns__requestSession *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__requestSession(struct soap*, struct tns__requestSession *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__requestSession(struct soap*, const char*, int, const struct tns__requestSession *, const char*);
SOAP_FMAC1 struct tns__requestSession * SOAP_FMAC2 soap_get_tns__requestSession(struct soap*, struct tns__requestSession *, const char*, const char*);
SOAP_FMAC1 struct tns__requestSession * SOAP_FMAC2 soap_in_tns__requestSession(struct soap*, const char*, struct tns__requestSession *, const char*);

#ifndef SOAP_TYPE_tns__Attribute
#define SOAP_TYPE_tns__Attribute (10)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Attribute(struct soap*, struct tns__Attribute const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Attribute(struct soap*, const struct tns__Attribute *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Attribute(struct soap*, struct tns__Attribute *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Attribute(struct soap*, struct tns__Attribute *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Attribute(struct soap*, const char*, int, const struct tns__Attribute *, const char*);
SOAP_FMAC1 struct tns__Attribute * SOAP_FMAC2 soap_get_tns__Attribute(struct soap*, struct tns__Attribute *, const char*, const char*);
SOAP_FMAC1 struct tns__Attribute * SOAP_FMAC2 soap_in_tns__Attribute(struct soap*, const char*, struct tns__Attribute *, const char*);

#ifndef SOAP_TYPE_tns__requestSessionResponse
#define SOAP_TYPE_tns__requestSessionResponse (11)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__requestSessionResponse(struct soap*, const struct tns__requestSessionResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__requestSessionResponse(struct soap*, const char*, int, const struct tns__requestSessionResponse *, const char*);
SOAP_FMAC1 struct tns__requestSessionResponse * SOAP_FMAC2 soap_get_tns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__requestSessionResponse * SOAP_FMAC2 soap_in_tns__requestSessionResponse(struct soap*, const char*, struct tns__requestSessionResponse *, const char*);

#ifndef SOAP_TYPE_ArrayOfstring
#define SOAP_TYPE_ArrayOfstring (12)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_ArrayOfstring(struct soap*, struct ArrayOfstring const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_ArrayOfstring(struct soap*, struct ArrayOfstring const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_ArrayOfstring(struct soap*, struct ArrayOfstring *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_ArrayOfstring(struct soap*, struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_ArrayOfstring(struct soap*, const char*, int, const struct ArrayOfstring *, const char*);
SOAP_FMAC1 struct ArrayOfstring * SOAP_FMAC2 soap_get_ArrayOfstring(struct soap*, struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC1 struct ArrayOfstring * SOAP_FMAC2 soap_in_ArrayOfstring(struct soap*, const char*, struct ArrayOfstring *, const char*);

#ifndef SOAP_TYPE_tns__getAttributesResponse
#define SOAP_TYPE_tns__getAttributesResponse (13)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__getAttributesResponse(struct soap*, const struct tns__getAttributesResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__getAttributesResponse(struct soap*, const char*, int, const struct tns__getAttributesResponse *, const char*);
SOAP_FMAC1 struct tns__getAttributesResponse * SOAP_FMAC2 soap_get_tns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__getAttributesResponse * SOAP_FMAC2 soap_in_tns__getAttributesResponse(struct soap*, const char*, struct tns__getAttributesResponse *, const char*);

#ifndef SOAP_TYPE_ArrayOfAttribute
#define SOAP_TYPE_ArrayOfAttribute (14)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_ArrayOfAttribute(struct soap*, struct ArrayOfAttribute const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_ArrayOfAttribute(struct soap*, struct ArrayOfAttribute const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_ArrayOfAttribute(struct soap*, struct ArrayOfAttribute *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_ArrayOfAttribute(struct soap*, struct ArrayOfAttribute *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_ArrayOfAttribute(struct soap*, const char*, int, const struct ArrayOfAttribute *, const char*);
SOAP_FMAC1 struct ArrayOfAttribute * SOAP_FMAC2 soap_get_ArrayOfAttribute(struct soap*, struct ArrayOfAttribute *, const char*, const char*);
SOAP_FMAC1 struct ArrayOfAttribute * SOAP_FMAC2 soap_in_ArrayOfAttribute(struct soap*, const char*, struct ArrayOfAttribute *, const char*);

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (15)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getAttributesResponse
#define SOAP_TYPE_PointerTotns__getAttributesResponse (16)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__getAttributesResponse(struct soap*, const char *, int, struct tns__getAttributesResponse *const*, const char *);
SOAP_FMAC1 struct tns__getAttributesResponse ** SOAP_FMAC2 soap_get_PointerTotns__getAttributesResponse(struct soap*, struct tns__getAttributesResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__getAttributesResponse ** SOAP_FMAC2 soap_in_PointerTotns__getAttributesResponse(struct soap*, const char*, struct tns__getAttributesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__requestSessionResponse
#define SOAP_TYPE_PointerTotns__requestSessionResponse (17)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__requestSessionResponse(struct soap*, const char *, int, struct tns__requestSessionResponse *const*, const char *);
SOAP_FMAC1 struct tns__requestSessionResponse ** SOAP_FMAC2 soap_get_PointerTotns__requestSessionResponse(struct soap*, struct tns__requestSessionResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__requestSessionResponse ** SOAP_FMAC2 soap_in_PointerTotns__requestSessionResponse(struct soap*, const char*, struct tns__requestSessionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__Attribute
#define SOAP_TYPE_PointerTotns__Attribute (18)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__Attribute(struct soap*, struct tns__Attribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__Attribute(struct soap*, struct tns__Attribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__Attribute(struct soap*, struct tns__Attribute **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__Attribute(struct soap*, struct tns__Attribute **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__Attribute(struct soap*, const char *, int, struct tns__Attribute *const*, const char *);
SOAP_FMAC1 struct tns__Attribute ** SOAP_FMAC2 soap_get_PointerTotns__Attribute(struct soap*, struct tns__Attribute **, const char*, const char*);
SOAP_FMAC1 struct tns__Attribute ** SOAP_FMAC2 soap_in_PointerTotns__Attribute(struct soap*, const char*, struct tns__Attribute **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfstring
#define SOAP_TYPE_PointerToArrayOfstring (19)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToArrayOfstring(struct soap*, struct ArrayOfstring *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToArrayOfstring(struct soap*, struct ArrayOfstring *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToArrayOfstring(struct soap*, const char *, int, struct ArrayOfstring *const*, const char *);
SOAP_FMAC1 struct ArrayOfstring ** SOAP_FMAC2 soap_get_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **, const char*, const char*);
SOAP_FMAC1 struct ArrayOfstring ** SOAP_FMAC2 soap_in_PointerToArrayOfstring(struct soap*, const char*, struct ArrayOfstring **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (20)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToxsd__string(struct soap*, char ***);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC1 char *** SOAP_FMAC2 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC1 char *** SOAP_FMAC2 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfAttribute
#define SOAP_TYPE_PointerToArrayOfAttribute (21)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToArrayOfAttribute(struct soap*, struct ArrayOfAttribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToArrayOfAttribute(struct soap*, struct ArrayOfAttribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToArrayOfAttribute(struct soap*, struct ArrayOfAttribute **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToArrayOfAttribute(struct soap*, struct ArrayOfAttribute **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToArrayOfAttribute(struct soap*, const char *, int, struct ArrayOfAttribute *const*, const char *);
SOAP_FMAC1 struct ArrayOfAttribute ** SOAP_FMAC2 soap_get_PointerToArrayOfAttribute(struct soap*, struct ArrayOfAttribute **, const char*, const char*);
SOAP_FMAC1 struct ArrayOfAttribute ** SOAP_FMAC2 soap_in_PointerToArrayOfAttribute(struct soap*, const char*, struct ArrayOfAttribute **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (22)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (23)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_string(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_string(struct soap*, const char*, char **, const char*);
#endif

/* end of soapH.h */
