/* soapStub.h
   Generated by gSOAP 2.2.3b from Authentication.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef soapStub_H
#define soapStub_H

/* Types With Custom (De)serializers: */

/* Enumerations */

#ifndef _SOAP_Enum_
#define _SOAP_Enum_
enum Enum_ {false_ = 0, true_ = 1};
#endif

/* Classes and Structs */

#ifndef _SOAP_ArrayOfAttribute
#define _SOAP_ArrayOfAttribute
/* Array of tns:Attribute schema type: */
struct ArrayOfAttribute
{
	struct tns__Attribute *__ptr;
	int __size;
	int __offset;
};
#endif

#ifndef _SOAP_tns__getAttributesResponse
#define _SOAP_tns__getAttributesResponse
struct tns__getAttributesResponse
{
	struct ArrayOfAttribute *_result;
};
#endif

#ifndef _SOAP_ArrayOfstring
#define _SOAP_ArrayOfstring
/* Array of xsd:string schema type: */
struct ArrayOfstring
{
	char **__ptr;
	int __size;
	int __offset;
};
#endif

#ifndef _SOAP_tns__requestSessionResponse
#define _SOAP_tns__requestSessionResponse
struct tns__requestSessionResponse
{
	char *_result;
};
#endif

#ifndef _SOAP_tns__Attribute
#define _SOAP_tns__Attribute
struct tns__Attribute
{
	char *name;
	struct ArrayOfstring *values;
};
#endif

#ifndef _SOAP_tns__requestSession
#define _SOAP_tns__requestSession
struct tns__requestSession
{
	struct ArrayOfstring *attributes;
	char *prefix;
	char *postfix;
	enum Enum_ denySSO;
};
#endif

#ifndef _SOAP_tns__getAttributes
#define _SOAP_tns__getAttributes
struct tns__getAttributes
{
	char *sessionId;
};
#endif

#ifndef _SOAP_SOAP_ENV__Header
#define _SOAP_SOAP_ENV__Header
/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};
#endif

#ifndef _SOAP_SOAP_ENV__Code
#define _SOAP_SOAP_ENV__Code
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;
	char *SOAP_ENV__Node;
	char *SOAP_ENV__Role;
};
#endif

#ifndef _SOAP_SOAP_ENV__Fault
#define _SOAP_SOAP_ENV__Fault
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;
	char *faultstring;
	char *faultactor;
	char *detail;
	struct SOAP_ENV__Code *SOAP_ENV__Code;
	char *SOAP_ENV__Reason;
	char *SOAP_ENV__Detail;
};
#endif

/* Typedefs */
typedef char *xsd__string;
typedef enum Enum_ xsd__boolean;

/* Variables */

/* Remote Methods */

SOAP_FMAC1 int SOAP_FMAC2 tns__requestSession(struct soap*, struct ArrayOfstring *, char *, char *, enum Enum_, struct tns__requestSessionResponse *);

SOAP_FMAC1 int SOAP_FMAC2 tns__getAttributes(struct soap*, char *, struct tns__getAttributesResponse *);

/* Stubs */

SOAP_FMAC1 int SOAP_FMAC2 soap_call_tns__requestSession(struct soap*, const char*, const char*, struct ArrayOfstring *, char *, char *, enum Enum_, struct tns__requestSessionResponse *);

SOAP_FMAC1 int SOAP_FMAC2 soap_call_tns__getAttributes(struct soap*, const char*, const char*, char *, struct tns__getAttributesResponse *);

/* Skeletons */

SOAP_FMAC1 int SOAP_FMAC2 soap_serve(struct soap*);

SOAP_FMAC1 int SOAP_FMAC2 soap_serve_tns__requestSession(struct soap*);

SOAP_FMAC1 int SOAP_FMAC2 soap_serve_tns__getAttributes(struct soap*);
#endif

/* end of soapStub.h */
