package no.feide.moria.directory;

/**
 * @author Cato Olsen Superclass for all exceptions generated by the directory
 *         manager.
 */
public class DirectoryManagerException
extends Exception {

    /**
     * Constructor.
     * @param message The exception message.
     */
    public DirectoryManagerException(String message) {

        super(message);
        
    }

}